config/routes.rb
Rails.application.routes.draw do
  post 'books/new'
  get 'home/about' => 'homes#about'
  get 'home/index' => 'homes#index'

  devise_for :users
  root to: 'homes#top'
  root to: 'home#about'
  resources :books, only: [:edit, :create, :index, :show, :update, :destroy] do
  end
  resources :users, only: [:index, :show, :edit, :update] do
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user

  validates :title, presence: true
  validates :body, presence: true,length: { maximum: 200 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  attachment :profile_image



  validates :name, uniqueness: true,
                   length: { minimum: 2, maximum: 20 }
  validates :introduction, length: { maximum: 50 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  protected

  def after_sign_in_path_for(resource)
    user_path(resource)
  end



  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :name])
    devise_parameter_sanitizer.permit(:sign_in, keys: [:name])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!

  def new
    @book = Book.new
    @user = User.new
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] = "You have created book successfully."
       redirect_to book_path(@book)
    else
      @user = current_user
      @books = Book.all
      render :index
    end
  end

  def index
    @book = Book.new
    @books = Book.all
    @user = current_user
  end

  def show
    @booknew = Book.new
    @book = Book.find(params[:id])
    @user = @book.user
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user == current_user
      render "edit"
    else
      redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "You have updated book successfully."
    redirect_to book_path(@book.id)
    else
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
  def about
  end
  def index
    @book = Book.new
    @books = Book.all
    @user = current_user
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!


  def index
    @user = current_user
    @book = Book.new
    @users = User.all
  end
  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
  end
  def edit
    @user = User.find(params[:id])
    if @user == current_user
      render "edit"
    else
      redirect_to user_path(current_user.id)
    end
  end
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "You have updated user successfully."
    redirect_to user_path(@user.id)
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_list.html.erb
<div class="col-md-3">
<h2 class="profile-name">Userinfo</h2>
<%= attachment_image_tag user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %>
<table class="table">
  <tbody>
    <tr>
      <th>name</th>
      <th><%= user.name %></th>
    </tr>
    <tr>
      <th>introduction</th>
      <th><%= user.introduction %></th>
    </tr>
  </tbody>
</table>
<%= link_to edit_user_path(user) do %>
<i class="btn btn-outline-secondary btn-block fas fa-user-cog"></i>
<% end %>
<h2 class="mt-3">New book</h2>
<% if @book.errors.any? %>
  <%= @book.errors.count %>件のerrorが発生しました
  <% @book.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %>
<%= form_with model: book, local: true do |f| %>
<div class="form-group">
  <label for="book_title">Title</label>
  <%= f.text_field :title, class:"form-control" %>
</div>
<div class="form-group">
  <label for="book_body">Opinion</label>
  <%= f.text_field :body, class:"form-control" %>
</div>
<div class="form-group">
  <br><%= f.submit 'Create Book', class: "btn btn-success" %></br>
</div>
<% end %>
</div>

app/views/books/edit.html.erb
<div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
  <h1>Editing Book</h1>
  <% if @book.errors.any? %>
  <%= @book.errors.count %>件のerrorが発生しました
  <% @book.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %>
  <%= form_with model:@book, local:true do |f| %>
    <label for="inputTitle">Title</label><br>
    <%= f.text_field :title, autofocus: true, id:"book_title", placeholder:"", class:"form-control" %><br>
    <label for="inputOpinion">Opinion</label><br>
    <%= f.text_field :body, autofocus: true, id:"book_body", placeholder:"", class:"form-control" %><br>
    <%= f.submit "Update Book", class: "btn btn-success" %>
  <% end %>
  <%= link_to "Show", book_path(@book.id) %> | <%= link_to "Back", books_path %>
</div>

app/views/books/index.html.erb
<%= render 'books/list', book: @book, user: current_user %>
    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @books.each do |book| %>
          <tr>
            <td><%= link_to  user_path(book.user) do %>
                <%= attachment_image_tag book.user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %>
                <% end %>
            </td>
            <td><%= link_to book.title, book_path(book.id) %>
            </td>
            <td><%= book.body %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/books/new.html.erb
<%= render 'books/list', book: @book %>
<div class="col-md-8 offset-md-1">
  <h2>Books</h2>
  <table class="table table-hover table-inverse">
    <thead>
      <tr>
        <th></th>
        <th>Title</th>
        <th>Opinion</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td><%= attachment_image_tag @user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %></td>
        <td></td>
        <td></td>
      </tr>
    </tbody>
  </table>
</div>

app/views/books/show.html.erb
<%= render 'books/list', book: @booknew, user: @user %>
<div class="col-md-8 offset-md-1">
  <h2>Book detail</h2>
  <table class="table">
    <tbody>
      <tr>
        <td>
          <%= attachment_image_tag @user, :profile_image %>
          <%= image_tag('no_image.jpg') %>
          <br><%= link_to @user.name, user_path(@user.id) %>
        </td>
        <td><%= link_to @book.title, book_path(@book.id) %></td>
        <td><%= @book.body %></td>
        <% if @user.id == current_user.id %>
        <td>
          <%= link_to "Edit", edit_book_path(@book.id), class: "btn btn-sm btn-success" %>
        </td>
        <td>
          <%= link_to "Destroy", book_path(@book), method: :delete, "data-confirm" => "本当に削除しますか？", class: "btn btn-sm btn-danger" %>
        </td>
        <% end %>
      </tr>
    </tbody>
  </table>
</div>

app/views/homes/about.html.erb
<div class="container">
  <div class="row">
    <h1 class="px-3 mx-auto">
        Welcome to
        <i class="fas fa-book">
        </i>
        <strong>Bookers</strong>
        !
    </h1>
  </div>
</div>

app/views/homes/index.html.erb
<%= render 'books/list', book: @book %>
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @books.each do |book| %>
          <tr>
            <td><%= link_to  user_path(book.user) do %>
                <%= attachment_image_tag @user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %>
                <% end %>
            </td>
            <td><%= link_to book.title, book_path(book.id) %>
            </td>
            <td><%= book.body %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/homes/top.html.erb
<div class="container">
        <div class="row">
          <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
            <h1>
               welcome to
              <i class="fas fa-book">
              </i>
              <strong>Bookers</strong>
               !!
              </h1>
              <p>
                In
                <i class="fas fa-book">
                </i>
                <strong>Bookers</strong>
                ,
              </p>
              <p>you can share and exchange your opinions , inpressions , and emotions</p>
              <p> about various books!</p>
              <div class="btn-wrapper col-10 mx-auto">
              <div class="row">
                <a class="btn btn-info btn-sm btn-block mb-3 sign_in" href="/users/sign_in">Log in</a>
              </div>
              <div class="row">
                <a class="btn btn-success btn-sm btn-block sign_up" href="/users/sign_up">Sign Up</a>
              </div>
            </div>
          </div>
        </div>
      </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>


  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <a class="navbar-brand" href="/">
            <span>Bookers</span>
          </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="true" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse show" id="navbarNavDropdown" style>
            <ul class="navbar-nav ml-auto">
            <% if user_signed_in? %>
            <li>
              <%= link_to 'Home', user_path(current_user.id), class: "fas fa-home nav-link text-light" %>
            </li>
            <li>
              <%= link_to 'Users', users_path, class: "fas fa-users nav-link text-light" %>
            </li>
            <li>
              <%= link_to 'Books', books_path, class: "fas fa-book-open nav-link text-light" %>
            </li>
            <li>
              <%= link_to "logout", destroy_user_session_path, method: :delete, class: "fas fa-sign-out-alt nav-link text-light" %>
            </li>
            <% else %>
            <li>
              <%= link_to "Home", root_path, class: "fas fa-home nav-link text-light" %>
            </li>
            <li>
              <%= link_to "About", home_about_path, class: "fas fa-link nav-link text-link" %>
            </li>
            <li>
              <%= link_to "sign up", new_user_registration_path, class: "fas fa-user-plus nav-link text-light" %>
            </li>
            <li>
              <%= link_to "login", new_user_session_path, class: "fas fa-sign-in-alt nav-link text-light" %>
            </li>
            <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <main>
      <% if flash[:notice] %>
        <p><%= flash[:notice] %></p>
      <% end %>
      <div class="container px-5 px-sm-0">
        <div class="row">
          <%= yield %>
        </div>
      </div>
    </main>
    <footer>
      <div class="container mt-5">
        <div class="row">
          <div class="mx-auto">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/users/edit.html.erb
<% if @user.id == current_user.id %>
<div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
  <h2><strong>User info</strong></h2>
  <% if @user.errors.any? %>
  <%= @user.errors.count %>件のerrorが発生しました
  <% @user.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %>
  <%= form_with model:@user, local:true do |f| %>
    <label for="inputName">Name</label><br>
    <%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"名前", class:"form-control" %><br>
    <label for="inputImage">Image</label><br>
    <%= f.attachment_field :profile_image, placeholder: "プロフィール画像" %><br>
    <label for="inputIntroduction">Introduction</label><br>
    <%= f.text_field :introduction, autofocus: true, id:"inputIntroduction", class:"form-control" %><br>
    <%= f.submit "Update User", class: "btn btn-secondary" %>
  <% end %>
</div>
<% end %>

app/views/users/index.html.erb
<%= render 'books/list', book: @book, user: current_user %>
<div class="col-md-8 offset-md-1">
  <h2>Users</h2>
  <table class="table">
    <thead>
      <tr>
        <th>image</th>
        <th>name</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
      <% @users.each do |user| %>
      <tr>
        <td><%= attachment_image_tag user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %></td>
        <td><%= user.name %></td>
        <td><%= link_to "Show", user_path(user.id) %></td>
      </tr>
      <tr></tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/users/show.html.erb
<%= render 'books/list', book: @book, user: @user %>
<div class="col-md-8 offset-md-1">
  <h2>Book</h2>
  <table class="table table-hover table-inverse">
    <thead>
      <tr>
        <th></th>
        <th>Title</th>
        <th>Opinion</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
      <% @books.each do |book| %>
      <tr>
        <td><%= link_to  user_path(book.user) do %>
            <%= attachment_image_tag @user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %>
            <% end %>
        </td>
        <td><%= link_to book.title, book_path(book.id) %>
        </td>
        <td><%= book.body %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>